export const columns = [
  {
    key: "id",
    label: "Id",
  },
  {
    key: "name",
    label: "Name",
  },
  {
    key: "age",
    label: "Age",
  },
  {
    key: "gender",
    label: "Gender",
  },
  {
    key: "email",
    label: "Email",
  },
  {
    key: "status",
    label: "Status",
  },
];

export const rowData = [
  {
    id: 1,
    name: "John Doe",
    age: 28,
    gender: "Male",
    email: "john.doe@example.com",
    status: "Active",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 34,
    gender: "Female",
    email: "jane.smith@example.com",
    status: "Inactive",
  },
  {
    id: 3,
    name: "Alice Johnson",
    age: 14,
    gender: "Female",
    email: "alice.johnson@example.com",
    status: "Active",
  },
  {
    id: 4,
    name: "Bob Brown",
    age: 30,
    gender: "Male",
    email: "bob.brown@example.com",
    status: "Expired",
  },
  {
    id: 5,
    name: "Charlie White",
    age: 40,
    gender: "Male",
    email: "charlie.white@example.com",
    status: "Expired",
  },
  {
    id: 6,
    name: "Gardek Wilson",
    age: 25,
    gender: "Male",
    email: "wilsone.Gardek@example.com",
    status: "Inactive",
  },
  {
    id: 7,
    name: "Diana Prince",
    age: 32,
    gender: "Female",
    email: "diana.prince@example.com",
    status: "Active",
  },
  {
    id: 8,
    name: "Bruce Wayne",
    age: 38,
    gender: "Male",
    email: "bruce.wayne@example.com",
    status: "Inactive",
  },
  {
    id: 9,
    name: "Clark Kent",
    age: 36,
    gender: "Male",
    email: "clark.kent@example.com",
    status: "Active",
  },
  {
    id: 10,
    name: "Lois Lane",
    age: 33,
    gender: "Female",
    email: "lois.lane@example.com",
    status: "Expired",
  },
  {
    id: 11,
    name: "Barry Allen",
    age: 29,
    gender: "Male",
    email: "barry.allen@example.com",
    status: "Active",
  },
  {
    id: 12,
    name: "Iris West",
    age: 28,
    gender: "Female",
    email: "iris.west@example.com",
    status: "Inactive",
  },
  {
    id: 13,
    name: "Alexander Jay",
    age: 68,
    gender: "Female",
    email: "Alexander.Jay@example.com",
    status: "Expired",
  },
  {
    id: 14,
    name: "Oke LaLaLand",
    age: 50,
    gender: "Male",
    email: "lalaland@example.com",
    status: "Expired",
  },
];
